[package]
name = "mymove"
version = "0.0.1"

[dependencies]
AptosStdlib = { local = "/data/aptos-core/aptos-move/framework/aptos-stdlib" }
MoveStdlib = { local = "/data/diem/language/move-stdlib" }
#MoveStdlib = { git = "https://github.com/move-language/move.git", subdir = "language/move-stdlib", rev = "main" }

[addresses]
std =  "0x1"
