[package]
name = "mymove"
version = "0.0.0"

[dependencies]
MoveStdlib = { local = "./move-stdlib" }
MoveNursery = { local = "./move-stdlib/nursery" }
#MoveStdlib = { git = "https://github.com/move-language/move.git", subdir = "language/move-stdlib", rev = "main" }
#MoveNursery = { git = "https://github.com/move-language/move.git", subdir="language/move-stdlib/nursery", rev = "main"}

[addresses]
std =  "0x1"
