[package]
name = "ManagedFungibleToken"
version = "0.0.0"

[addresses]
aptos_framework = "0x1"
aptos_token_objects = "0x4"
example_addr = "0x91a7e539806ff68caf1bcba305c8f694182898949c581586b4c9676e6bf35392"

[dependencies]
AptosFramework = { local = "../../../framework/aptos-framework" }
AptosTokenObjects = { local = "../../../framework/aptos-token-objects" }
ManagedFungibleAsset = { local = "../managed_fungible_asset" }
