[package]
name = "Drand lottery"
version = "0.0.1"

[dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }
#AptosStdlib = { local = "../../framework/aptos-stdlib" }

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
drand = "0x91a7e539806ff68caf1bcba305c8f694182898949c581586b4c9676e6bf35392"
