[package]
name = "CommonAccount"
version = "1.0.0"

[dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }

[addresses]
common_account = "0x91a7e539806ff68caf1bcba305c8f694182898949c581586b4c9676e6bf35392"
